window.__CATEGORIAS__ = {
  'Economia e Atividade': '#e11d48',
  'Emprego e Renda': '#2563eb',
  'Preços, Juros e Poder de Compra': '#005f15ff',
  'Finanças Públicas e Tributação': '#7423ff',
  'Saúde': '#00788eff',
  'Educação': '#003ae7',
  'Tecnologia e Inovação': '#86a400ff',
  'Segurança Pública': '#dc0000ff',
  'Meio Ambiente': '#0d9d00ff',
  'Habitação, Saneamento e Vida Urbana': '#9d009aff',
  'Pobreza e Desenvolvimento Humano': '#5b2700ff',
  'Governança, Democracia e Instituições': '#bf0026ff',
  'Setor Externo e Comércio': '#00a682ff',
  'Empresas, Infraestrutura e Produtividade': '#3928bdff',
  'Mercados Financeiros e Risco': '#431d00ff',
  'Moedas e Criptoativos': '#d68400',
  'Commodities': '#856d00ff',
  'Habitação, Inclusão Digital e Condições Sociais': '#4f46e5',
  'Relações Internacionais e Soft Power': '#be123c'
};
